<?php

declare(strict_types=1);

/**
 * 관리자 라이더 목록·상세 목업 (키: 라이더 ID).
 *
 * @return array<string, array<string, mixed>>
 */
function mock_riders_by_id(): array
{
    return [
        'R-104418' => [
            'id' => 'R-104418',
            'login_id' => 'rider104418',
            'name' => '권성진',
            'phone_masked' => '010-****-4418',
            'email' => 'rider4418@example.com',
            'birth_masked' => '1992-**-**',
            'team' => '강서남부 A조',
            'team_code' => 'gangseo_a',
            'primary_platform' => 'baemin',
            'platforms' => [
                ['code' => 'baemin', 'label' => '배달의민족', 'connected' => true, 'linked_id' => 'BM-88291'],
                ['code' => 'coupang', 'label' => '쿠팡이츠', 'connected' => true, 'linked_id' => 'CP-102938'],
            ],
            'status' => 'active',
            'status_label' => '활동 중',
            'join_date' => '2024-03-12',
            'vehicle_type' => '오토바이',
            'vehicle_number_masked' => '서울 **가 4418',
            'address_short' => '서울 강서구',
            'bank_name' => '국민은행',
            'bank_account_masked' => '123456-**-****12',
            'account_holder' => '권성진',
            'kyc_status' => 'verified',
            'kyc_label' => '본인인증 완료',
            'id_verified_at' => '2024-03-12',
            'contract_signed_at' => '2024-03-15',
            'insurance_name' => '시간제 보험(배민 연동)',
            'insurance_expires' => '2026-06-30',
            'last_login_at' => '2026-05-10 13:58',
            'last_delivery_at' => '2026-05-10 13:42',
            'orders_mtd' => 612,
            'orders_last_week' => 148,
            'rating_avg' => 4.92,
            'penalty_points' => 0,
            'withdrawal_hold' => false,
            'admin_memo' => '정산 이슈 없음. 우수 라이더.',
            'recent_activity' => [
                ['at' => '2026-05-10 13:42', 'type' => '배달 완료', 'detail' => '강서구 · 단가 피크'],
                ['at' => '2026-05-10 09:10', 'type' => '로그인', 'detail' => '앱 · Android'],
                ['at' => '2026-05-09 18:22', 'type' => '정산 반영', 'detail' => '일간 정산서 업로드 반영'],
            ],
        ],
        'R-203274' => [
            'id' => 'R-203274',
            'login_id' => 'rider203274',
            'name' => '민세훈',
            'phone_masked' => '010-****-3274',
            'email' => 'min3274@example.com',
            'birth_masked' => '1995-**-**',
            'team' => '강서남부 B조',
            'team_code' => 'gangseo_b',
            'primary_platform' => 'coupang',
            'platforms' => [
                ['code' => 'coupang', 'label' => '쿠팡이츠', 'connected' => true, 'linked_id' => 'CP-77201'],
                ['code' => 'baemin', 'label' => '배달의민족', 'connected' => false, 'linked_id' => ''],
            ],
            'status' => 'active',
            'status_label' => '활동 중',
            'join_date' => '2025-01-08',
            'vehicle_type' => '전동킥보드',
            'vehicle_number_masked' => '—',
            'address_short' => '서울 양천구',
            'bank_name' => '신한은행',
            'bank_account_masked' => '110-***-******01',
            'account_holder' => '민세훈',
            'kyc_status' => 'verified',
            'kyc_label' => '본인인증 완료',
            'id_verified_at' => '2025-01-08',
            'contract_signed_at' => '2025-01-10',
            'insurance_name' => '시간제 보험',
            'insurance_expires' => '2026-08-15',
            'last_login_at' => '2026-05-10 12:10',
            'last_delivery_at' => '2026-05-10 11:55',
            'orders_mtd' => 428,
            'orders_last_week' => 102,
            'rating_avg' => 4.78,
            'penalty_points' => 1,
            'withdrawal_hold' => false,
            'admin_memo' => '쿠팡 위주. 배민 재연동 요청 접수(목업).',
            'recent_activity' => [
                ['at' => '2026-05-10 11:55', 'type' => '배달 완료', 'detail' => '목동 · 일반'],
                ['at' => '2026-05-08 16:00', 'type' => '경고', 'detail' => '노쇼 1회(자동 기록)'],
            ],
        ],
        'R-880647' => [
            'id' => 'R-880647',
            'login_id' => 'rider880647',
            'name' => '노동현',
            'phone_masked' => '010-****-0647',
            'email' => 'dh0647@example.com',
            'birth_masked' => '1988-**-**',
            'team' => '강서남부 A조',
            'team_code' => 'gangseo_a',
            'primary_platform' => 'baemin',
            'platforms' => [
                ['code' => 'baemin', 'label' => '배달의민족', 'connected' => true, 'linked_id' => 'BM-120044'],
            ],
            'status' => 'suspended',
            'status_label' => '일시 정지',
            'join_date' => '2023-11-02',
            'vehicle_type' => '오토바이',
            'vehicle_number_masked' => '경기 **바 5647',
            'address_short' => '경기 부천시',
            'bank_name' => '우리은행',
            'bank_account_masked' => '1002-***-******89',
            'account_holder' => '노동현',
            'kyc_status' => 'verified',
            'kyc_label' => '본인인증 완료',
            'id_verified_at' => '2023-11-02',
            'contract_signed_at' => '2023-11-05',
            'insurance_name' => '시간제 보험',
            'insurance_expires' => '2026-04-10',
            'last_login_at' => '2026-05-07 08:40',
            'last_delivery_at' => '2026-05-07 08:35',
            'orders_mtd' => 0,
            'orders_last_week' => 0,
            'rating_avg' => 4.55,
            'penalty_points' => 6,
            'withdrawal_hold' => true,
            'admin_memo' => '고객 클레임 2건 누적 — RM 검토 중(목업).',
            'recent_activity' => [
                ['at' => '2026-05-07 09:00', 'type' => '계정 조치', 'detail' => '일시 정지 적용'],
                ['at' => '2026-05-06 21:12', 'type' => '클레임', 'detail' => '음식 파손 신고 접수'],
            ],
        ],
        'R-551102' => [
            'id' => 'R-551102',
            'login_id' => 'rider551102',
            'name' => '이하늘',
            'phone_masked' => '010-****-1102',
            'email' => 'sky1102@example.com',
            'birth_masked' => '2000-**-**',
            'team' => '영등포',
            'team_code' => 'ydp',
            'primary_platform' => 'baemin',
            'platforms' => [
                ['code' => 'baemin', 'label' => '배달의민족', 'connected' => true, 'linked_id' => 'BM-551102'],
                ['code' => 'coupang', 'label' => '쿠팡이츠', 'connected' => true, 'linked_id' => 'CP-551102'],
            ],
            'status' => 'active',
            'status_label' => '활동 중',
            'join_date' => '2025-08-20',
            'vehicle_type' => '자전거',
            'vehicle_number_masked' => '—',
            'address_short' => '서울 영등포구',
            'bank_name' => '농협',
            'bank_account_masked' => '302-****-****-90',
            'account_holder' => '이하늘',
            'kyc_status' => 'verified',
            'kyc_label' => '본인인증 완료',
            'id_verified_at' => '2025-08-20',
            'contract_signed_at' => '2025-08-22',
            'insurance_name' => '미가입(검토 필요)',
            'insurance_expires' => '',
            'last_login_at' => '2026-05-10 14:20',
            'last_delivery_at' => '2026-05-10 14:05',
            'orders_mtd' => 355,
            'orders_last_week' => 81,
            'rating_avg' => 4.88,
            'penalty_points' => 0,
            'withdrawal_hold' => false,
            'admin_memo' => '',
            'recent_activity' => [
                ['at' => '2026-05-10 14:05', 'type' => '배달 완료', 'detail' => '여의도'],
            ],
        ],
        'R-440012' => [
            'id' => 'R-440012',
            'login_id' => 'rider440012',
            'name' => '최유진',
            'phone_masked' => '010-****-0012',
            'email' => 'yj4400@example.com',
            'birth_masked' => '1998-**-**',
            'team' => '마포',
            'team_code' => 'mapo',
            'primary_platform' => 'coupang',
            'platforms' => [
                ['code' => 'coupang', 'label' => '쿠팡이츠', 'connected' => true, 'linked_id' => 'CP-440012'],
            ],
            'status' => 'leave_request',
            'status_label' => '휴·탈퇴 요청',
            'join_date' => '2024-07-01',
            'vehicle_type' => '오토바이',
            'vehicle_number_masked' => '서울 **나 9012',
            'address_short' => '서울 마포구',
            'bank_name' => '하나은행',
            'bank_account_masked' => '123-******-**234',
            'account_holder' => '최유진',
            'kyc_status' => 'verified',
            'kyc_label' => '본인인증 완료',
            'id_verified_at' => '2024-07-01',
            'contract_signed_at' => '2024-07-03',
            'insurance_name' => '시간제 보험',
            'insurance_expires' => '2026-12-01',
            'last_login_at' => '2026-05-09 19:00',
            'last_delivery_at' => '2026-05-09 18:50',
            'orders_mtd' => 120,
            'orders_last_week' => 34,
            'rating_avg' => 4.9,
            'penalty_points' => 0,
            'withdrawal_hold' => false,
            'admin_memo' => '5/12 최종 배달 후 계약 종료 예정(목업).',
            'recent_activity' => [
                ['at' => '2026-05-09 10:00', 'type' => '요청', 'detail' => '휴·탈퇴 요청 접수'],
            ],
        ],
        'R-991877' => [
            'id' => 'R-991877',
            'login_id' => 'rider991877',
            'name' => '정우성',
            'phone_masked' => '010-****-1877',
            'email' => 'ws9918@example.com',
            'birth_masked' => '1991-**-**',
            'team' => '강서남부 A조',
            'team_code' => 'gangseo_a',
            'primary_platform' => 'baemin',
            'platforms' => [
                ['code' => 'baemin', 'label' => '배달의민족', 'connected' => true, 'linked_id' => 'BM-991877'],
            ],
            'status' => 'active',
            'status_label' => '활동 중',
            'join_date' => '2022-05-18',
            'vehicle_type' => '오토바이',
            'vehicle_number_masked' => '인천 **다 1877',
            'address_short' => '인천 서구',
            'bank_name' => 'IBK기업은행',
            'bank_account_masked' => '010-******-**901',
            'account_holder' => '정우성',
            'kyc_status' => 'verified',
            'kyc_label' => '본인인증 완료',
            'id_verified_at' => '2022-05-18',
            'contract_signed_at' => '2022-05-20',
            'insurance_name' => '시간제 보험',
            'insurance_expires' => '2026-09-01',
            'last_login_at' => '2026-05-10 06:30',
            'last_delivery_at' => '2026-05-10 06:15',
            'orders_mtd' => 702,
            'orders_last_week' => 168,
            'rating_avg' => 4.95,
            'penalty_points' => 0,
            'withdrawal_hold' => false,
            'admin_memo' => '팀 리더 후보(목업).',
            'recent_activity' => [
                ['at' => '2026-05-10 06:15', 'type' => '배달 완료', 'detail' => '검단 · 새벽'],
            ],
        ],
        'R-112233' => [
            'id' => 'R-112233',
            'login_id' => 'rider112233',
            'name' => '김라이더',
            'phone_masked' => '010-****-2233',
            'email' => 'kimride@example.com',
            'birth_masked' => '1994-**-**',
            'team' => '강서남부 B조',
            'team_code' => 'gangseo_b',
            'primary_platform' => 'baemin',
            'platforms' => [
                ['code' => 'baemin', 'label' => '배달의민족', 'connected' => true, 'linked_id' => 'BM-112233'],
                ['code' => 'coupang', 'label' => '쿠팡이츠', 'connected' => true, 'linked_id' => 'CP-112233'],
            ],
            'status' => 'active',
            'status_label' => '활동 중',
            'join_date' => '2025-11-01',
            'vehicle_type' => '오토바이',
            'vehicle_number_masked' => '서울 **라 2233',
            'address_short' => '서울 구로구',
            'bank_name' => '토스뱅크',
            'bank_account_masked' => '1000-****-****',
            'account_holder' => '김라이더',
            'kyc_status' => 'pending',
            'kyc_label' => '추가 서류 대기',
            'id_verified_at' => '2025-11-01',
            'contract_signed_at' => '',
            'insurance_name' => '시간제 보험',
            'insurance_expires' => '2026-11-30',
            'last_login_at' => '2026-05-10 10:00',
            'last_delivery_at' => '2026-05-10 09:48',
            'orders_mtd' => 210,
            'orders_last_week' => 52,
            'rating_avg' => 4.7,
            'penalty_points' => 0,
            'withdrawal_hold' => false,
            'admin_memo' => '계약서 전자서명 재요청(목업).',
            'recent_activity' => [
                ['at' => '2026-05-09 15:00', 'type' => '알림', 'detail' => '서류 업로드 독려 문자 발송'],
            ],
        ],
        'R-771203' => [
            'id' => 'R-771203',
            'login_id' => 'rider771203',
            'name' => '박지민',
            'phone_masked' => '010-****-1203',
            'email' => 'jm7712@example.com',
            'birth_masked' => '1999-**-**',
            'team' => '영등포',
            'team_code' => 'ydp',
            'primary_platform' => 'coupang',
            'platforms' => [
                ['code' => 'coupang', 'label' => '쿠팡이츠', 'connected' => true, 'linked_id' => 'CP-771203'],
            ],
            'status' => 'offboarded',
            'status_label' => '계약 종료',
            'join_date' => '2023-02-14',
            'vehicle_type' => '전동킥보드',
            'vehicle_number_masked' => '—',
            'address_short' => '서울 동작구',
            'bank_name' => '카카오뱅크',
            'bank_account_masked' => '3333-**-******90',
            'account_holder' => '박지민',
            'kyc_status' => 'verified',
            'kyc_label' => '본인인증 완료',
            'id_verified_at' => '2023-02-14',
            'contract_signed_at' => '2023-02-16',
            'insurance_name' => '—',
            'insurance_expires' => '',
            'last_login_at' => '2026-04-28 22:00',
            'last_delivery_at' => '2026-04-28 21:40',
            'orders_mtd' => 0,
            'orders_last_week' => 0,
            'rating_avg' => 4.6,
            'penalty_points' => 0,
            'withdrawal_hold' => false,
            'admin_memo' => '2026-04-30 계약 만료 처리.',
            'recent_activity' => [
                ['at' => '2026-04-30 09:00', 'type' => '계정', 'detail' => '계약 종료 · 앱 접속 불가'],
            ],
        ],
    ];
}

/** @return list<array<string, mixed>> */
function mock_riders_list_rows(): array
{
    $all = mock_riders_by_id();
    $rows = array_values($all);
    usort($rows, static function (array $a, array $b): int {
        return strcmp((string) ($a['name'] ?? ''), (string) ($b['name'] ?? ''));
    });

    return $rows;
}

function mock_rider_platform_label(string $code): string
{
    return match ($code) {
        'baemin' => '배민',
        'coupang' => '쿠팡',
        default => $code,
    };
}

function mock_rider_status_badge_class(string $status): string
{
    return match ($status) {
        'active' => 'success',
        'suspended' => 'danger',
        'leave_request' => 'warning',
        'offboarded' => 'dark',
        default => 'primary',
    };
}
