<?php

declare(strict_types=1);

return [
    'dashboard' => ['title' => '대시보드', 'view' => 'dashboard'],
    'docs/manual' => ['title' => '매뉴얼', 'view' => 'manual_docs'],
    'settlement/upload' => ['title' => '엑셀 업로드', 'view' => 'settlement_upload'],
    'settlement/upload-detail' => ['title' => '업로드 상세', 'view' => 'settlement_upload_detail'],
    'settlement/history' => ['title' => '업로드 이력', 'view' => 'settlement_history'],
    'settlement/fees' => ['title' => '정산 수수료 내역', 'view' => 'settlement_fees'],
    'settlement/fee-detail' => ['title' => '정산 수수료 상세', 'view' => 'settlement_fee_detail'],
    'settlement/withholding' => ['title' => '원천세 대상자 명세', 'view' => 'withholding_report'],
    'settlement/fee-report' => ['title' => '수수료·차감 통합 조회', 'view' => 'fee_report'],
    'settlement/platform-fee' => ['title' => '플랫폼 수수료 내역', 'view' => 'platform_fee_history'],
    'settlement/order-details' => ['title' => '오더별 상세 내역', 'view' => 'order_detail_list'],
    'promotion' => ['title' => '프로모션 지급', 'view' => 'promotion'],
    'promotion/detail' => ['title' => '프로모션 지급 상세', 'view' => 'promotion_detail'],
    'promotion/calculator' => ['title' => '프로모션 계산기', 'view' => 'promotion_calculator'],
    'deduction/agency-fee' => ['title' => '수수료 설정', 'view' => 'deduction_agency_fee'],
    'deduction/debts' => ['title' => '미수금 원장', 'view' => 'debt_list'],
    'deduction/lease-fees' => ['title' => '리스 수수료 배분', 'view' => 'lease_fee_report'],
    'withdrawal/list' => ['title' => '출금 신청 목록', 'view' => 'withdrawal_list'],
    'withdrawal/settings' => ['title' => '수수료 설정(관리)', 'view' => 'withdrawal_settings'],
    'settlement/statement' => ['title' => '정산명세서', 'view' => 'settlement_statement'],
    'withdrawal/download' => ['title' => '출금 다운로드', 'view' => 'withdrawal_download'],
    'withdrawal/complete' => ['title' => '출금 처리 완료', 'view' => 'withdrawal_complete'],
    'withdrawal/wallet-ledger' => ['title' => '지갑 입출금', 'view' => 'wallet_ledger'],
    'withdrawal/agency-payout' => ['title' => '대리점 자체 인출', 'view' => 'agency_payout'],
    'withdrawal/daily-payout' => ['title' => '일일정산 지급 리스트', 'view' => 'daily_payout'],
    'withdrawal/proxy' => ['title' => '출금 대행', 'view' => 'withdrawal_proxy'],
    'withdrawal/payment-setup' => ['title' => '결제 설정(카드·계좌)', 'view' => 'payment_setup'],
    'content/notices' => ['title' => '공지 관리', 'view' => 'content_notices'],
    'content/banners' => ['title' => '광고 배너', 'view' => 'content_banners'],
    'riders/list' => ['title' => '라이더 관리', 'view' => 'riders_list'],
    'riders/detail' => ['title' => '라이더 상세', 'view' => 'riders_detail'],
    'system/orgs' => ['title' => '조직 관리(총판·대리점)', 'view' => 'system_orgs'],
    'system/admins' => ['title' => '관리자 계정·권한', 'view' => 'system_admins'],
    'system/team' => ['title' => '대표·서브계정 관리', 'view' => 'org_accounts'],
    'system/codes' => ['title' => '코드/마스터', 'view' => 'system_codes'],
    'system/settlement-excel' => ['title' => '정산 엑셀 열기 암호', 'view' => 'system_settlement_excel'],
    'system/audit' => ['title' => '감사 로그', 'view' => 'system_audit'],
    'system/manual-adjust' => ['title' => '정산/잔액 수동 조정', 'view' => 'system_manual_adjust'],
    'system/pg-fee' => ['title' => '수수료 현황', 'view' => 'pg_fee_config'],
    'system/pg-integration' => ['title' => 'PG 연동·결제통지', 'view' => 'pg_integration'],
    'system/pg-logs' => ['title' => 'PG 결제 이력', 'view' => 'pg_logs'],
    'system/firm-integration' => ['title' => '펌뱅킹 연동', 'view' => 'firm_integration'],
    'system/integration-mode' => ['title' => '연동 모드', 'view' => 'integration_mode'],
    'system/permissions' => ['title' => '권한 관리', 'view' => 'permissions'],
    'system/statistics' => ['title' => '통계', 'view' => 'statistics'],
    'system/messages' => ['title' => '문자·알림톡', 'view' => 'messages'],
    // 세무대리 전용 — 고용·산재 예수금 확인·수집(2026-09-01)
    'tax/dashboard' => ['title' => '고용·산재 예수금', 'view' => 'tax_dashboard'],
];
